apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: status-page-api-db
  labels:
    app: status-page-api-db
spec:
  selector:
    matchLabels:
      app: status-page-api-db
  serviceName: "database"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: status-page-api-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: postgres:16.2
        name: postgres
        resources: {}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
        envFrom:
          - configMapRef:
              name: db-config
          - secretRef:
              name: db-secrets
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 25Gi
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-api-db
  labels:
    app: status-page-api-db
spec:
  ports:
  - port: 5432
  selector:
    app: status-page-api-db
