apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-page-api
  name: status-page-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-page-api
  template:
    metadata:
      labels:
        app: status-page-api
    spec:
      containers:
      - image: registry.scs.community/status-page/status-page-api@sha256:39ece8255c306870c20aaa39bbabd9cc7774d3af823a1b728d99363a4841abac
        name: status-page-api
        resources: {}
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: api-config
          - secretRef:
              name: api-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-api
  labels:
    app: status-page-api
spec:
  selector:
    app: status-page-api
  ports:
  - port: 3000
