apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-page-api
  name: status-page-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-page-api
  template:
    metadata:
      labels:
        app: status-page-api
    spec:
      containers:
      - image: registry.scs.community/status-page/status-page-api@sha256:9af80058b0cb020dbfd490b1f8b37818edb60298487bc6e03f302510576dd253
        name: status-page-api
        resources: {}
        ports:
          - containerPort: 3000
          - containerPort: 9000
        envFrom:
          - configMapRef:
              name: api-config
          - secretRef:
              name: api-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-api
  labels:
    app: status-page-api
spec:
  selector:
    app: status-page-api
  ports:
  - port: 3000
    name: api
  - port: 9000
    name: metrics
