apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-page-api
  name: status-page-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-page-api
  template:
    metadata:
      labels:
        app: status-page-api
    spec:
      containers:
      - image: registry.scs.community/status-page/status-page-api@sha256:bb1c8f04f16471511cf56e7111bd358fba528de1321b8056fe8f18e6cb3a0516
        name: status-page-api
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 64Mi
            cpu: 25m
        ports:
          - containerPort: 3000
          - containerPort: 9000
        envFrom:
          - configMapRef:
              name: api-config
          - secretRef:
              name: api-secrets
        volumeMounts:
          - name: provisioning-dir
            mountPath: /etc/status-page-api
      volumes:
        - name: provisioning-dir
          configMap:
            name: api-provisioning-files
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-api
  labels:
    app: status-page-api
spec:
  selector:
    app: status-page-api
  ports:
  - port: 3000
    name: api
  - port: 9000
    name: metrics
