apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-page-dex
  name: status-page-dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-page-dex
  template:
    metadata:
      labels:
        app: status-page-dex
    spec:
      containers:
      - image: dexidp/dex:v2.38.0
        name: dex
        resources:
          requests:
            memory: 64Mi
            cpu: 25m
        ports:
          - containerPort: 5556
          - containerPort: 5558
        volumeMounts:
          - name: config-dir
            mountPath: /etc/dex
        envFrom:
          - configMapRef:
              name: dex-config
          - secretRef:
              name: dex-secrets
          - configMapRef:
              name: web-config
          - secretRef:
              name: web-secrets
        args: [dex, serve, /etc/dex/config.yaml]
      volumes:
        - name: config-dir
          configMap:
            name: dex-config-files
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-dex
  labels:
    app: status-page-dex
spec:
  selector:
    app: status-page-dex
  ports:
  - port: 5556
    name: web
  - port: 5558
    name: telemetry
