apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-page-oathkeeper
  name: status-page-oathkeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-page-oathkeeper
  template:
    metadata:
      labels:
        app: status-page-oathkeeper
    spec:
      containers:
      - image: oryd/oathkeeper:v0.40.7
        name: oathkeeper
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 64Mi
            cpu: 25m
        ports:
          - containerPort: 4455
          - containerPort: 4456
          - containerPort: 9000
        volumeMounts:
          - name: config-dir
            mountPath: /etc/oathkeeper
        command: [oathkeeper, serve]
        args: [-c, /etc/oathkeeper/config.yaml]
      volumes:
        - name: config-dir
          configMap:
            name: oathkeeper-config-files
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-oathkeeper
  labels:
    app: status-page-oathkeeper
spec:
  selector:
    app: status-page-oathkeeper
  ports:
  - port: 4455
    name: proxy
  - port: 4456
    name: api
  - port: 9000
    name: metrics
