apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scs-status-page-dex
  name: scs-status-page-dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scs-status-page-dex
  template:
    metadata:
      labels:
        app: scs-status-page-dex
    spec:
      containers:
      - image: dexidp/dex:v2.37.0
        name: dex
        resources: {}
        ports:
          - containerPort: 5556
        volumeMounts:
          - name: config-dir
            mountPath: /etc/dex
        envFrom:
          - secretRef:
              name: dex-secrets
          - secretRef:
              name: web-secrets
              optional: true
          - configMapRef:
              name: web-config
              optional: true
        command: [dex]
        args: [serve, /etc/dex/config.yaml]
      volumes:
        - name: config-dir
          configMap:
            name: dex-config
---
apiVersion: v1
kind: Service
metadata:
  name: scs-status-page-dex
  labels:
    app: scs-status-page-dex
spec:
  selector:
    app: scs-status-page-dex
  ports:
  - port: 5556
