apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scs-status-page-api
  name: scs-status-page-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scs-status-page-api
  template:
    metadata:
      labels:
        app: scs-status-page-api
    spec:
      containers:
      - image: registry.scs.community/status-page/status-page-api@sha256:895aa2b58d6e30f05d80940fad352610bb69816fa2b7b391b77005e5884ff8fa
        name: scs-status-page-api
        resources: {}
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: api-config
          - secretRef:
              name: api-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: scs-status-page-api
  labels:
    app: scs-status-page-api
spec:
  selector:
    app: scs-status-page-api
  ports:
  - port: 3000
