apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scs-status-page-reverse-proxy
  name: scs-status-page-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scs-status-page-reverse-proxy
  template:
    metadata:
      labels:
        app: scs-status-page-reverse-proxy
    spec:
      containers:
      - image: caddy:2.6.4
        name: caddy
        resources: {}
        ports:
          - containerPort: 80
        volumeMounts:
          - name: config-dir
            mountPath: /etc/caddy/
      volumes:
        - name: config-dir
          configMap:
            name: caddy-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scs-status-page-reverse-proxy
  name: scs-status-page-reverse-proxy
spec:
  selector:
    app: scs-status-page-reverse-proxy
  ports:
  - port: 80
  type: LoadBalancer

