apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-page-web
  name: status-page-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-page-web
  template:
    metadata:
      labels:
        app: status-page-web
    spec:
      containers:
      - image: registry.scs.community/status-page/status-page-web:v1.0.1
        name: status-page-web
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 64Mi
            cpu: 25m
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: web-config
          - secretRef:
              name: web-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-web
  labels:
    app: status-page-web
spec:
  selector:
    app: status-page-web
  ports:
    - port: 8080
