apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - prometheus.yaml

configMapGenerator:
  - name: grafana-config
    envs:
      - grafana/grafana.env

  - name: grafana-datasource-provisioning
    files:
      - grafana/datasources.yaml

  - name: grafana-dashboard-provisioning
    files:
      - grafana/dashboards.yaml

  - name: grafana-dashboards
    files:
      - grafana/dashboards/9628_rev7.json
      - grafana/dashboards/10826_rev1.json
      - grafana/dashboards/Oathkeeper-1718203458929.json
      - grafana/dashboards/Dex-1718271569643.json

  - name: prometheus-config-files
    files:
      - prometheus/prometheus.yml



secretGenerator:
  - name: grafana-secrets
    envs:
      - grafana/grafana-secrets.env
