apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- issuer.yaml
- ingress.yaml
- ../../app

secretGenerator:
  - name: db-secrets
    envs:
      - database/database.env

  - name: dex-secrets
    envs:
      - dex/dex.env

  - name: web-secrets
    envs:
      - web/web-secrets.env

configMapGenerator:
  - name: api-config
    envs:
      - api/api.env

  - name: dex-config
    files:
      - dex/config.yaml

  - name: oathkeeper-config
    files:
      - oathkeeper/config.yaml
      - oathkeeper/rules.yaml

  - name: web-config
    envs:
      - web/web.env

namespace: status-page
