apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: grafana-dashboards
    files:
      - grafana/dashboards/9628_rev7.json
      - grafana/dashboards/10826_rev1.json
      - grafana/dashboards/Oathkeeper-1720685662895.json
      - grafana/dashboards/Dex-1720687900405.json
      - grafana/dashboards/API-1718710757996.json
