apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
  name: status-page
spec:
  ingressClassName: traefik
  rules:
  - host: status.213.131.230.142.nip.io
    http:
      paths:
      - backend:
          service:
            name: status-page-web
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: idp.213.131.230.142.nip.io
    http:
      paths:
      - backend:
          service:
            name: status-page-dex
            port:
              number: 5556
        path: /
        pathType: Prefix
  - host: api.213.131.230.142.nip.io
    http:
      paths:
      - backend:
          service:
            name: status-page-oathkeeper
            port:
              number: 4455
        path: /
        pathType: Prefix
  tls:
    - hosts:
        - status.213.131.230.142.nip.io
        - idp.213.131.230.142.nip.io
        - api.213.131.230.142.nip.io
      secretName: status-page-ingress-tls
