{
 "title": "API",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate(status_page_api_request_duration_seconds_bucket[$__rate_interval])) by(le,method)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total requests increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (increase(status_page_api_requests_total[$__rate_interval])) by(code, method)",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  { "title": "Request - Response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request size increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(status_page_api_request_size_bytes_sum[$__rate_interval])) by(code, method)",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Response size increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(status_page_api_response_size_bytes_sum[$__rate_interval])) by(code, method)",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Request size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum (rate(status_page_api_request_size_bytes_bucket[$__rate_interval])) by(le,method)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum (rate(status_page_api_response_size_bytes_bucket[$__rate_interval])) by(le,method)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}