{
 "title": "Oathkeeper",
 "tags": [
  "auth",
  "authorization",
  "proxy"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ory_oathkeeper_requests_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total requests increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(ory_oathkeeper_requests_total[$__rate_interval])) by (status_code, method)",
     "legendFormat": "{{method}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Unauthorized Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(ory_oathkeeper_requests_total{status_code=\"401\"}[$__rate_interval])) by (method,status_code)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}