issuer: http://dex.test

storage:
  type: memory

web:
  http: 0.0.0.0:5556

frontend:
  issuer: SCS Status Page
  theme: dark

logger:
  level: "debug"
  format: "text"

# https://dexidp.io/docs/connectors/github/
connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: $GITHUB_CLIENT_ID
      clientSecret: $GITHUB_CLIENT_SECRET
      redirectURI: http://dex.test/callback
      scopes:
        - user
        - read:org
      loadAllGroups: true
