issuer: http://dex.test

storage:
  type: memory

web:
  http: 0.0.0.0:5556

# telemetry:
#   http: 0.0.0.0:5558

frontend:
  issuer: SCS Status Page
  theme: dark

logger:
  level: "debug"
  format: "text"

staticClients:
  - id: example-app
    redirectURIs:
      - 'http://127.0.0.1:5555/callback'
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

# https://dexidp.io/docs/connectors/github/
connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: $GITHUB_CLIENT_ID
      clientSecret: $GITHUB_CLIENT_SECRET
      redirectURI: http://dex.test/callback
      scopes:
        - user
        - read:org
      loadAllGroups: true
