issuer: https://status-idp.k8s.scs.community

storage:
  type: memory

web:
  http: 0.0.0.0:5556
  allowedOrigins:
    - "{{ .Env.DEX_ALLOWED_ORIGINS }}"

frontend:
  issuer: SCS Status Page
  theme: dark

telemetry:
  http: 0.0.0.0:5558

logger:
  level: "info"
  format: "text"

staticClients:
  - id: "{{ .Env.STATUS_PAGE_WEB_OIDC_ID }}"
    public: true
    redirectURIs:
      - "{{ .Env.STATUS_PAGE_WEB_OIDC_REDIRECT_URI }}"
    name: "{{ .Env.CLIENT_NAME }}"

# https://dexidp.io/docs/connectors/github/
connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: "{{ .Env.GITHUB_CLIENT_ID }}"
      clientSecret: "{{ .Env.GITHUB_CLIENT_SECRET }}"
      redirectURI: https://status-idp.k8s.scs.community/callback
      scopes:
        - user
        - read:org
      loadAllGroups: true
      orgs:
        - name: "{{ .Env.GITHUB_ORG }}"
