serve:
  proxy:
    port: 4455
    cors:
      enabled: true
      allowed_origins:
        - http://web.localhost:8080
        - http://localhost:4200
      allow_credentials: true
      allowed_methods:
        - POST
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
  api:
    port: 4456
  prometheus:
    port: 9000
    hide_request_paths: true
access_rules:
  repositories:
    - file:///etc/oathkeeper/rules.yaml

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
  jwt:
    enabled: true
    config:
      jwks_urls:
        - http://status-page-dex:5556/keys
      trusted_issuers:
        - http://dex.localhost:8080
