apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../app/
  - reverse-proxy.yaml

secretGenerator:
  - name: api-secrets
    envs:
      - api/database-connection.env

  - name: db-secrets
    envs:
      - database/database.env

  - name: dex-secrets
    envs:
      - dex/dex.env

configMapGenerator:
  - name: api-config
    envs:
      - api/api.env

  - name: dex-config
    files:
      - dex/config.yaml

  - name: caddy-config
    files:
      - caddy/Caddyfile

  - name: oathkeeper-config
    files:
      - oathkeeper/config.yaml
      - oathkeeper/rules.yaml

namespace: status-page
